/*
 * This source file was generated by the Gradle 'init' task
 */
package passwordmanager.cipher;

import org.junit.jupiter.api.Test;

import passwordmanager.core.Cipher;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class CipherTest {
    @Test
    void encryptDecrypt() {
    	byte[] sampleData = "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn".getBytes();
    	String password = "Secret password";
    	byte[] encrypted = new Cipher.Encryptor(sampleData, password).getEncrypted();
    	byte[] decrypted = new Cipher.Decryptor(encrypted, password).getDecrypted();
    	
    	// Padding (with spaces) is applied, so we must strip the decrypted array
    	decrypted = Arrays.copyOfRange(decrypted, 0, sampleData.length);
    	
    	System.out.println(new String(decrypted));
    	
    	assertTrue(Arrays.equals(decrypted, sampleData));
    }
}
